spring:
  liquibase:
    change-log: classpath:liquibase/db.changelog.xml
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/buy_recipes
    username: postgres
    password: <your_password_here>
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: /